import Head from "next/head";
import MainLayout from "../layouts/MainLayout";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Logs | Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <p className="dark:text-white text-black">dashboard</p>
      </div>
    </div>
  );
}

// eslint-disable-next-line react/display-name
Home.getLayout = (page: any) => (
  <MainLayout>
    {page}
  </MainLayout>
);
