import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p className="first-letter:text-4xl first-letter:font-bold first-letter:float-left">tailwind css 2.2.4 jit in here 😉</p>
    </div>
  );
}
